VARIABLES_ETL:
  COLUMNS_TO_SAVE:
    - PassengerId
    - Pclass
    - Name
    - Sex
    - Age
    - SibSp
    - Parch
    - Ticket
    - Fare
    - Cabin
    - Embarked
  DOUBLE_CAST:
    - PassengerId
    - Age
    - SibSp
    - Parch
    - Fare
  STR_CAST:
    - Pclass
    - Sex
    - Embarked
  TARGET: Survived
  ID: PassengerId

PREPROCESS:
  PIPELINE_NAME: pipeline.pkl

TRAIN:
  MODEL_NAME: CatBoostClassifier

PREDICT:
  COLUMNS_SAVE:
    - insert_date_ci
    - Survived_probability
