VARIABLES_ETL:
  COLUMNS_TO_SAVE:
    - PassengerId
    - Pclass
    - Name
    - Sex
    - Age
    - SibSp
    - Parch
    - Ticket
    - Fare
    - Cabin
    - Embarked
  DOUBLE_CAST:
    - PassengerId
    - Age
    - SibSp
    - Parch
    - Fare
  STR_CAST:
    - Pclass
    - Sex
    - Embarked
  TARGET: Survived
  ID: PassengerId

PREPROCESS:
  PIPELINE_NAME: pipeline.pkl

TRAIN:
  MODEL_NAME: CatBoostClassifier

PREDICT:
  COLUMNS_RENAME:
    gross_revenue_sh_year1: ccv_sh
    gross_revenue_mh_year1: ccv_mh
    gross_revenue_lh_year1: ccv_lh
  COLUMNS_SAVE:
    - cid
    - ccv
    - ccv_sh
    - ccv_mh
    - ccv_lh
    - churn_probability
    - insert_date_ci
