VARIABLES_ETL:
  COLUMNS_TO_SAVE:
    - PassengerId
    - Pclass
    - Name
    - Sex
    - Age
    - SibSp
    - Parch
    - Ticket
    - Fare
    - Cabin
    - Embarked
  DOUBLE_CAST:
    - PassengerId
    - Age
    - SibSp
    - Parch
    - Fare
  STR_CAST:
    - Pclass
    - Sex
    - Embarked
  LABELS: 
    - promoter_binary
    - detractor_binary
  ID: respondent_id

PREPROCESS:
  PIPELINE_NAME: pipeline.pkl

TRAIN:
  MODEL_NAME: 
    - Promoters
    - Detractors
  FEATURES:
    - Pclass
    - Name
    - Sex
    - Age
    - SibSp
    - Parch
    - Ticket
    - Fare
    - Cabin
    - Embarked
  

PREDICT:
  COLUMNS_SAVE:
    - insert_date_ci
    - Survived_probability
