--- # Configuration file - Train
paths:
    bucket_name: 'iberia-data-lake'
    bucket_name_sbx: 'iberiasbx-data-lake'
    dir_read_data: 'customer/customer_models_data_v2/'
    dir_main_data: 'customer/churn_model_v2/'
    dir_po_data: 'customer/churn/po_churn_cltv/'
    dir_prediction: 'customer/churn/prediction/'
    dir_plots: '../plots/'
    dir_reports: '../reports/'
    dir_models: '../models/'
files:
    model_churn: 'churn_classifier.pkl'
    imputer: 'imp_regressor.pkl'
    scaler: 'trans_regressor.pkl'
    model_cltv: 'nn_cltv_regressor.h5'
preprocessing:
    columns: ['id_golden_record', 'coupon_usage_code', 'prime_ticket_num', 'pnr_resiber', 'pnr_amadeus',
              'gross_revenue','ticket_sale_date', 'date_creation_pnr_resiber', 'num_bags', 'eur_bags', 'num_seats',
              'eur_seats', 'num_upgs', 'eur_upgs', 'num_others', 'eur_others', 'ff_number_by_idgoldenrecord',
              'birth_date', 'pax_type_ind', 'num_days_anticipation', 'ind_reason_business',
              'num_hours_in_destination', 'loc_dep_date_scheduled', 'loc_arr_date_scheduled', 'loc_arr_time_scheduled',
              'loc_dep_time_scheduled', 'itinerary_od', 'date_creation_idgoldenrecord', 'haul', 'class_code',
              'ff_tier', 'pax_demand_space', 'ff_group', 'op_carrier_code', 'op_flight_num', 'flag_misconnection_misc',
              'flag_dng', 'minutes_delay_arr', 'flight_cnld', 'mkt_permission', 'purchases_2015', 'purchases_2016',
              'purchases_2017', 'sales_channel']
train:
    test_size: 0.20
    val_test_size: 0.50
    opt_metric: 'recall'
    model_name: 'CatBoostClassifier'
    n_trials: 50
variables:
    target: 'churn'
    actual_value: 'gross_revenue_and_ancillaries_year1'
    columns_trend: ['gross_revenue_and_ancillaries']
    input_missing_mice:
        - last_flight
        - sh_haul
        - mh_haul
        - lh_haul
        - purchases_2015
        - purchases_2016
        - purchases_2017
        - seniority
        - IB_pctg
        - max_minutes_delay_arr_year1
        - mean_deviation_flight_spent
    extra_features: 
        - age_bin
        - most_od_flown_tg
    eliminate_features:
        - age
        - most_od_flown
    cat_features: 
        - ff_tier
        - most_od_flown
    binary_features: 
        - flag_ibplus
        - is_corporate
        - is_resident
        - ind_direct_sale
        - mkt_permission
    discrete_features: 
        - frequency
        - n_ancillaries
        - seniority
        - last_purchase
        - last2_purchase
        - last3_purchase
        - last_flight
        - n_exchanges
        - n_not_travelled
        - n_refunded
        - purchases_2015
        - purchases_2016
        - purchases_2017
        - last_spent
        - n_destination_city_od
    cont_features: 
        - num_days_anticipation
        - num_hours_in_destination
        - loc_dep_weekend
        - ow_flights
        - gross_revenue_and_ancillaries
        - alone_flights
        - couple_flights
        - group_flights
        - summer_flights
        - winter_flights
        - fall_flights
        - spring_flights
        - sh_haul
        - mh_haul
        - lh_haul
        - economy
        - premium
        - business
        - mean_deviation_flight_spent
        - max_minutes_delay_arr_year1
        - revenue_avios
        - IB_pctg
        - mean_spend_year3
        - mean_spend_year2
        - mean_spend_year1
        - trend1_gross_revenue_and_ancillaries
        - trend2_gross_revenue_and_ancillaries
        - last_purchase1_2
        - last_purchase2_3
        - age